export const START_TODOS_LOADING = 'START_TODOS_LOADING';
export const STOP_TODOS_LOADING = 'STOP_TODOS_LOADING';
export const SET_TODOS = 'SET_TODOS';
export const SET_TODOS_ERROR = 'SET_TODOS_ERROR';