# Generated by Django 3.2.5 on 2021-07-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carmodel',
            table='cars',
        ),
    ]
